unit_6_terms = [
    "Industrialization",
    "Economic development",
    "Gross Domestic Product (GDP)",
    "Gross National Income (GNI)",
    "Formal economy",
    "Informal economy",
    "Core-periphery model",
    "Dependency theory",
    "World Systems Theory",
    "Development Gap",
    "Development Indicators",
    "Human Development Index (HDI)",
    "Gini Coefficient",
    "Modernization theory",
    "Rostow's Stages of Economic Growth",
    "Dependency ratio",
    "Deindustrialization",
    "Outsourcing",
    "Offshoring",
    "Globalization",
    "Neoliberalism",
    "Structural Adjustment Programs (SAPs)",
    "Export Processing Zones (EPZs)",
    "Special Economic Zones (SEZs)",
    "Free Trade Zones (FTZs)",
    "Foreign Direct Investment (FDI)",
    "Transnational corporations (TNCs)"
]